/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "lwpsxwnrbgrnyoqsrjaw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3cHN4d25yYmdybnlvcXNyamF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4MjQ0NzAsImV4cCI6MjA3NjQwMDQ3MH0.uGWSt3v71kmApG0GY-qZknNvnOlJh0n7d8o-vP1uOCk"